### PR TITLE
Update moose submodule and fixup deprecations

### PR DESCRIPTION
**Pull request by cticenhour**
This PR contains:

- An update to the MOOSE submodule
- Core restart/backup and `XolotlProblem::converged` changes from #8 as well as an addition to fit the new method signature from `SubProblem`
- Fixup for many deprecated parameters and objects in the test inputs
- Move to `ModulesApp::registerAllObjects` in the `coupling_xolotlApp.C` source
- Removal of a deprecated App-level parameter for DirichletBCs
- Switch to new MOOSE-namespaced `main` method in `main.C` and related adjustments

@SudiptaBiswas The main issue with #8 was that `XolotlProblem::converged` as-modified did not properly override the new version of `SubProblem::converged`, so the app was getting a premature "I'm converged!" signal. With these changes, all tests are passing on my macOS (ARM64) laptop. I think that PR should be closed in favor of this one.

@sblondel Could you give this a review and merge if you approve?

@sapitts Tagging you for awareness that this task is done, pending code review and merge.

### CODE REVIEW

**Comment by sblondel** [comment]
@cticenhour Perfect timing Casey! Sudipta and I were just having a meeting to discuss #8 when I saw your PR. We'll both test it and I'll approve it afterwards.

**Comment by sblondel** [comment]
@cticenhour I'm still having issues building on Sawtooth, I think it's related to my configuration but I can't figure out what I'm missing. I'll first ask you and if we can't figure it out I'll contact support.

Here are my modules:
```
Currently Loaded Modules:
  1) curl/7.61.1-gcc-12.3.0-5t73   3) zlib/1.2.13-gcc-12.3.0-c2ww    5) gmp/6.1.2-gcc-10.5.0-wep3    7) mpc/1.3.1-gcc-10.5.0-mpcb    9) gcc/12.3.0-gcc-10.5.0-vx2f
  2) ncurses/6.1-gcc-12.3.0-7zps   4) cmake/3.27.7-gcc-12.3.0-5cfk   6) mpfr/4.2.0-gcc-10.5.0-cec4   8) zstd/1.4.4-gcc-10.5.0-yue3  10) mvapich2/2.3.7-1-gcc-12.3.0
```
Then I get a warning during the coupling code compilation:
```
/usr/bin/ld: warning: libslepc.so.3.019, needed by /projects/NE_SciDAC/sawtooth_20231108/projects/coupling_xolotl_std/moose/framework/contrib/pcre/libpcre-opt.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libpetsc.so.3.019, needed by /projects/NE_SciDAC/sawtooth_20231108/projects/coupling_xolotl_std/moose/framework/contrib/pcre/libpcre-opt.so, not found (try using -rpath or -rpath-link)
```
And when I try to run the tests they crash:
```
test:kernels/2D.PF_as_master_1: /projects/NE_SciDAC/sawtooth_20231108/projects/coupling_xolotl_std/coupling_xolotl-opt: error while loading shared libraries: libslepc.so.3.019: cannot open shared object file: No such file or directory
```

**Comment by cticenhour** [comment]
That warning for `libslepc` looks as though you don't have a completely clean build. The `.3.019` at the end suggests that some library is trying to load SLEPc 3.19 (from PETSc 3.19), rather than the libraries associated with PETSc/SLEPc 3.20 as the newer version of MOOSE is using. Have you tried doing a deep git clean? This is destructive to files that git is ignoring or doesn't have committed, so I recommend committing or stashing away items that you want to preserve. Then you can perform:

```
git clean -xfd
```

in your coupling_xolotl directory, with 

```
git submodule foreach git clean -xfd
```

to clean kokkos, xolotl, and moose, and then a final

```
cd moose
git submodule foreach git clean -xfd
```

To clean the petsc and libmesh dirs in the moose directory. Also double-check that all submodules have been updated.

**Comment by cticenhour** [comment]
If this still leads to the warning and subsequent testing error, I can take a look on sawtooth at some point  today between meetings.

**Comment by sblondel** [comment]
@cticenhour Everything worked after the deep git clean, thank you!

@SudiptaBiswas Did you get a chance to test this version?

**Comment by SudiptaBiswas** [comment]
I only tested the change @cticenhour suggested to `converged` syntax. Everything works fine, both on mac and sawtooth.

**Review by sblondel — APPROVED** [review]
It looks all good

**Pull request merged**
